RailwaySystem/RailwaySystem/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('railway/', include('railway.urls')),
    path('train/', include('train.urls')),
]

# urlpatterns += staticfiles_urlpatterns()

RailwaySystem/railway/urls.py
from django.urls import path
from . import views

app_name = 'railway'
urlpatterns = [
    path('index/', views.index, name="index"),
    path('register/', views.register, name="register"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
]

RailwaySystem/train/urls.py
from django.urls import path
from . import views

app_name = 'train'
urlpatterns = [
    path('get-train/', views.getTrain, name="getTrain"),
    path('add-train/', views.createTrain, name="createTrain"),
    path('update-train/<str:id>/', views.updateTrain, name="updateTrain"),
    path('delete-train/<str:id>/', views.deleteTrain, name="deleteTrain"),

    #### route ####
    path('get-route/', views.getRoute, name="getRoute"),
    path('add-route/', views.createRoute, name="createRoute"),
    path('update-route/<int:id>/', views.updateRoute, name="updateRoute"),
    path('delete-route/<int:id>/', views.deleteRoute, name="deleteRoute"),

    #### station ####
    path('get-stations/', views.getStations, name="getStations"),
    path('add-station/', views.createStation, name="createStation"),
    path('update-station/<str:id>/', views.updateStation, name="updateStation"),
    path('delete-station/<str:id>/', views.deleteStation, name="deleteStation"),

    #### Route Station ####
    path('add-routestation/', views.createRouteStation, name="createRouteStation"),
    path('get-routestation/', views.getRouteStation, name="getRouteStation"),
    path('update-routestation/<int:id>/',
         views.updateRouteStation, name="updateRouteStation"),
    path('delete-routestation/<int:id>/',
         views.deleteRouteStatio, name="deleteRouteStatio"),
]

RailwaySystem/railway/models.py
from django.db import models

# Create your models here.

RailwaySystem/railway/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User, auth

# Create your views here.


def index(request):
    message = "Hello Priyanka!"
    return render(request, 'railway/index.html', {'message': message})


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return HttpResponseRedirect('/railway/index')
        else:
            return HttpResponseRedirect('railway/login')
    else:
        return render(request, 'railway/login.html')


def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        user = User.objects.create_user(
            username=username, password=password1, first_name=first_name, last_name=last_name, email=email)
        user.save()
        print("User created successfully!")
        return HttpResponseRedirect('/railway/index')

    else:
        return render(request, 'railway/register.html')


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/railway/index')

RailwaySystem/railway/templates/railway/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://use.fontawesome.com/d85834dac0.js"></script>
       <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="collapse navbar-collapse">
            <div class="navbar-header">
                <a href="#" class="navbar-brand" style="margin-left: 1rem;">Indian Railways Enquiry</a>
            </div>
            
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                {% if user.is_superuser %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'train:createTrain' %}">Add Trains</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'train:createStation' %}">Add Stations</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'train:createRouteStation' %}">Add Route Station</a>
                    </li>
                {% endif %}

                <li class="nav-item active">
                    <a class="nav-link" href="#">PNR Enquiry</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="#">Search Train</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Reserved Train Between Stations</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Seat Availability</a>
                </li>
              </ul>

              <span class="navbar-text">
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'railway:logout' %}">Logout</a>
                {% else %}
                    <a class="nav-link" href="{% url 'railway:login' %}">Login</a>
                {% endif %}
              </span>
              
        </div>
    </nav>
</body>
</html>

RailwaySystem/railway/templates/railway/index.html
{% extends 'railway/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{ message }}
</body>
</html>

RailwaySystem/railway/templates/railway/login.html
{% include 'railway/base.html' %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <h3 class="card-title">Login</h3>
            <form action="{% url 'railway:login' %}" method="POST" class="card card-sm">
                {% csrf_token %}
                <div class="card-body row no-gutters align-items-center">
                    <div class="mb-3">
                        <input type="text" name="username" placeholder="Username" class="form-control form-control-borderless">
                    </div>
                    <div class="mb-3">
                        <input type="password" name="password" placeholder="Password" class="form-control form-control-borderless">
                    </div>
                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary">Sign In</button>
                    </div>
                
                </div>
            </form>
        </div>
    </div>
</div>

RailwaySystem/railway/templates/railway/register.html
{% include 'railway/base.html' %}
    {% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <h3 class="card-title">Create Your Account</h3>
                <form action="{% url 'railway:register' %}" method="POST" class="card card-sm">
                    {% csrf_token %}
                    <div class="card-body row no-gutters align-items-center">
                        <div class="mb-3">
                            <input type="text" name="first_name" placeholder="First Name" class="form-control form-control-borderless">
                        </div>
                        
                        <div class="mb-3">
                            <input type="text" name="last_name" placeholder="Last Name" class="form-control form-control-borderless">
                        </div>

                        <div class="mb-3">
                            <input type="text" name="username" placeholder="Username" class="form-control form-control-borderless">
                        </div>

                        <div class="mb-3">
                            <input type="email" name="email" placeholder="Email" class="form-control form-control-borderless">
                        </div>

                        <div class="mb-3">
                            <input type="password" name="password1" placeholder="Password" class="form-control form-control-borderless">
                        </div>

                        <div class="mb-3">
                            <input type="password" name="password2" placeholder="Confirm Password" class="form-control form-control-borderless">
                        </div>

                        <div class="mb-3">
                            <button type="submit" class="btn btn-primary">Register</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>



    
        
            
    {% endblock %}