RailwaySystem/RailwaySystem/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('railway/', include('railway.urls')),
    path('train/', include('train.urls')),
]

# urlpatterns += staticfiles_urlpatterns()

RailwaySystem/train/urls.py
from django.urls import path
from . import views

app_name = 'train'
urlpatterns = [
    path('get-train/', views.getTrain, name="getTrain"),
    path('add-train/', views.createTrain, name="createTrain"),
    path('update-train/<str:id>/', views.updateTrain, name="updateTrain"),
    path('delete-train/<str:id>/', views.deleteTrain, name="deleteTrain"),

    #### route ####
    path('get-route/', views.getRoute, name="getRoute"),
    path('add-route/', views.createRoute, name="createRoute"),
    path('update-route/<int:id>/', views.updateRoute, name="updateRoute"),
    path('delete-route/<int:id>/', views.deleteRoute, name="deleteRoute"),

    #### station ####
    path('get-stations/', views.getStations, name="getStations"),
    path('add-station/', views.createStation, name="createStation"),
    path('update-station/<str:id>/', views.updateStation, name="updateStation"),
    path('delete-station/<str:id>/', views.deleteStation, name="deleteStation"),

    #### Route Station ####
    path('add-routestation/', views.createRouteStation, name="createRouteStation"),
    path('get-routestation/', views.getRouteStation, name="getRouteStation"),
    path('update-routestation/<int:id>/',
         views.updateRouteStation, name="updateRouteStation"),
    path('delete-routestation/<int:id>/',
         views.deleteRouteStatio, name="deleteRouteStatio"),
]

RailwaySystem/train/models.py
from django.db import models

# Create your models here.


class Train(models.Model):

    def __str__(self):
        return self.train_name

    train_number = models.CharField(primary_key=True, max_length=100)
    train_name = models.CharField(max_length=2000)
    route = models.ForeignKey(
        'Route', on_delete=models.CASCADE)

    class Meta:
        db_table = "trains"


class Route(models.Model):
    def __str__(self):
        return self.source_station + "--"+self.dest_station
        # return str(self.id)

    # route_id = models.CharField(max_length=50, unique=True)
    source_station = models.CharField(max_length=300)
    dest_station = models.CharField(max_length=300)

    class Meta:
        db_table = "routes"


class Station(models.Model):
    def __str__(self):
        return self.station_name

    station_id = models.AutoField(primary_key=True)
    station_name = models.CharField(max_length=50)

    class Meta:
        db_table = "stations"


class RouteStation(models.Model):
    def __str__(self):
        return str(self.train_number) + str(self.station_id) + str(self.route_id) + str(self.atime)

    train_number = models.ForeignKey('Train', on_delete=models.CASCADE)
    station_id = models.ForeignKey('Station', on_delete=models.CASCADE)
    route_id = models.ForeignKey('Route', on_delete=models.CASCADE)
    # order = models.IntegerField()
    atime = models.TimeField()

    class Meta:
        db_table = "route_station"

RailwaySystem/train/forms.py
from django import forms
from django.db import models
from django.forms import fields
from .models import Station, Train, Route, RouteStation


class TrainForm(forms.ModelForm):
    class Meta:
        model = Train
        fields = ['train_number', 'train_name', 'route']


class RouteForm(forms.ModelForm):
    class Meta:
        model = Route
        fields = ['source_station', 'dest_station']


class StationForm(forms.ModelForm):
    class Meta:
        model = Station
        fields = ['station_name']


class RouteStationForm(forms.ModelForm):
    class Meta:
        model = RouteStation
        fields = ['train_number', 'station_id', 'route_id', 'atime']

RailwaySystem/train/views.py
from typing import final
from django import forms
from django.http import request
from .models import RouteStation, Station, Train, Route
from django.shortcuts import redirect, render
from .forms import TrainForm, RouteForm, StationForm, RouteStationForm


def getTrain(request):
    allTrain = Train.objects.all().values()
    routeData = Route.objects.all().values()

    final_data = []
    for train in allTrain:
        data = {}
        for route in routeData:
            if(route['id'] == train['route_id']):
                data['source_station'] = route['source_station']
                data['dest_station'] = route['dest_station']
                data['train_number'] = train['train_number']
                data['train_name'] = train['train_name']

        final_data.append(data)

    return render(request, "train/get_train.html", {'final_data': final_data})


def createTrain(request):
    if request.method == 'POST':
        form = TrainForm(request.POST or None)

        if form.is_valid():
            form.save()
        else:
            pass
        return redirect("/train/get-train")
    else:
        routeData = Route.objects.all().values()
        form = TrainForm()
        return render(request, "train/addTrain.html", {'routeData': routeData, 'form': form})


def updateTrain(request, id):
    train_detail = Train.objects.get(train_number=id)

    form = TrainForm(request.POST or None, instance=train_detail)

    if form.is_valid():
        form.save()
        return redirect("/train/get-train")

    return render(request, "train/addTrain.html", {'form': form, 'train_detail': train_detail})


def deleteTrain(request, id):
    train_detail = Train.objects.get(train_number=id)

    if request.method == 'POST':
        train_detail.delete()
        return redirect("/train/get-train")

    return render(request, 'train/delete_train.html', {'train_detail': train_detail})


####### Route ######
def getRoute(request):
    routeData = Route.objects.all().values()
    return render(request, "train/get_route.html", {'routeData': routeData})


def createRoute(request):
    if request.method == 'POST':
        form = RouteForm(request.POST or None)

        if form.is_valid():
            form.save()
        else:
            pass
        return redirect("/train/get-route")
    else:
        form = RouteForm()
        return render(request, "train/addRoute.html", {'form': form})


def updateRoute(request, id):
    route_detail = Route.objects.get(id=id)

    form = RouteForm(request.POST or None, instance=route_detail)

    if form.is_valid():
        form.save()
        return redirect("/train/get-route")

    return render(request, "train/addRoute.html", {'form': form, 'route_detail': route_detail})


def deleteRoute(request, id):
    route_detail = Route.objects.get(id=id)
    print("Hiiiii Priyanka", id, request.method)
    if request.method == 'POST':

        route_detail.delete()
        return redirect("/train/get-route")

    return render(request, 'train/get_route.html', {'route_detail': route_detail})


######################### Station ##############################
def getStations(request):
    stationData = Station.objects.all().values()
    return render(request, "train/get_stations.html", {'stationData': stationData})


def createStation(request):
    if request.method == 'POST':
        form = StationForm(request.POST or None)

        if form.is_valid():
            form.save()
        else:
            pass
        return redirect("/train/get-stations")
    else:
        form = StationForm()
        return render(request, "train/addStation.html", {'form': form})


def updateStation(request, id):
    station_detail = Station.objects.get(pk=id)

    form = StationForm(request.POST or None, instance=station_detail)

    if form.is_valid():
        form.save()
        return redirect("/train/get-stations")

    return render(request, "train/addStation.html", {'form': form, 'station_detail': station_detail})


def deleteStation(request, id):
    station_detail = Station.objects.get(pk=id)

    if request.method == 'POST':
        station_detail.delete()
        return redirect("/train/get-stations")

    return render(request, 'train/delete_station.html', {'station_detail': station_detail})


#### Route stations ####
def getRouteStation(request):
    routestations = RouteStation.objects.all()
    # print(stationData)
    return render(request, "train/get_routestation.html", {'routestations': routestations})


def createRouteStation(request):
    if request.method == 'POST':
        form = RouteStationForm(request.POST or None)

        if form.is_valid():
            form.save()
        else:
            pass
        return redirect("/train/get-routestation")
    else:
        form = RouteStationForm()
        return render(request, "train/addRouteStation.html", {'form': form})


def updateRouteStation(request, id):
    routestation_detail = RouteStation.objects.get(pk=id)

    form = RouteStationForm(request.POST or None, instance=routestation_detail)

    if form.is_valid():
        form.save()
        return redirect("/train/get-routestation")

    return render(request, "train/addRouteStation.html", {'form': form, 'routestation_detail': routestation_detail})


def deleteRouteStatio(request, id):
    routestation_detail = RouteStation.objects.get(pk=id)

    if request.method == 'POST':
        routestation_detail.delete()
        return redirect("/train/get-routestation")

    return render(request, 'train/get_routestation.html', {'routestation_detail': routestation_detail})

RailwaySystem/train/templates/train/addRoute.html
{% include 'railway/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-3">
            <h3 class="card-title">Add / Edit Route</h3>
            <form action="#" method="post" class="card card-sm">
                {%csrf_token%}
                <div class="card-body row no-gutters align-items-center">
                    <div class="row mb-3">{{form}}</div>
                    <div class="col-auto">
                        <button type="submit" class="btn btn-success">Save</button>
                    </div>
                </div>
            </form>
                        
        </div>
    </div>
</div>
{% endblock %}

RailwaySystem/train/templates/train/addRouteStation.html
{% include 'railway/base.html' %}
{% block body%}

<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-3">
            <h3 class="card-title">Add / Edit route of station</h3>
            <form action="#" method="post" class="card card-sm">
                {%csrf_token%}
                <div class="card-body row no-gutters align-items-center">
                    <div class="row mb-3">{{form}}</div>
                    <div class="col-auto">
                        <button type="submit" class="btn btn-success">Save</button>
                    </div>
                </div>
            </form>
                        
        </div>
    </div>
</div>
{% endblock %}

RailwaySystem/train/templates/train/addStation.html
{% include 'railway/base.html' %}
{% block body%}

<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-3">
            <h3 class="card-title">Add / Edit Station</h3>
            <form action="#" method="post" class="card card-sm">
                {%csrf_token%}
                <div class="card-body row no-gutters align-items-center">
                    <div class="row mb-3">{{form}}</div>
                    <div class="col-auto">
                        <button type="submit" class="btn btn-success">Save</button>
                    </div>
                </div>
            </form>
                        
        </div>
    </div>
</div>
{% endblock %}

RailwaySystem/train/templates/train/addTrain.html
{% include 'railway/base.html' %}
{% block body%}

<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-3">
            <h3 class="card-title">Add / Edit Train</h3>
            <form action="#" method="post" class="card card-sm">
                {%csrf_token%}
                <div class="card-body row no-gutters align-items-center">
                    <div class="row mb-3">{{form}}</div>
                    <div class="col-auto">
                        <button type="submit" class="btn btn-success">Save</button>
                    </div>
                </div>
            </form>
                        
        </div>
    </div>
</div>
{% endblock %}

<!-- <div class="card-body row no-gutters align-items-center">
    <div class="row mb-3">
        <label for="TrainNumber" class="form-label">Train Number</label>
        <div class="col-sm-12">
            <input type="text" name="train_number">
        </div>
    </div>
    <div class="row mb-3">
        <label for="TrainName" class="form-label">Train Name</label>
        <div class="col-sm-12">
            <input type="text" name="train_name">
        </div>
    </div>
    <div class="row mb-3">
        <label for="selectroute" class="form-label">Select Route</label>
        <div class="col-sm-12">
            <select name="route" class="form-select">
            {% for i in routeData %}
                <option value="{{ i.id }}">{{i.source_station}}--{{i.dest_station}} </option>
            {% endfor %}
            </select>
        </div>
    </div>
    
    <div class="col-auto">
        <button type="submit" class="btn btn-success">Save</button>
    </div>
</div> -->

RailwaySystem/train/templates/train/delete_route.html
{% include 'railway/base.html' %}
{% block body%}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-3">
            <h3 class="card-title">Delete Train</h3>
            <form method="POST" class="card card-sm">
                {% csrf_token %}
                <div class="card-body row no-gutters align-items-center">
                    <p>Are you sure want to delete <b>{{route_detail.source_station}} -- {{route_detail.dest_station}} </b> route?</p>
                    <div class="col-auto"><button type="submit" class="btn btn-danger">Delete</button></div>
                </div>
            </form>
        </div>
    </div>
</div>
   
{% endblock %}

RailwaySystem/train/templates/train/delete_routestation.html
{% include 'railway/base.html' %}
{% block body%}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-3">
            <h3 class="card-title">Delete route of station</h3>
            <form method="POST" class="card card-sm">
                {% csrf_token %}
                <div class="card-body row no-gutters align-items-center">
                    <p>Are you sure want to delete <b>{{train_detail.train_name}}</b> route of station?</p>
                    <div class="col-auto"><button type="submit" class="btn btn-danger">Delete</button></div>
                </div>
            </form>
        </div>
    </div>
</div>
   
{% endblock %}

RailwaySystem/train/templates/train/delete_station.html
{% include 'railway/base.html' %}
{% block body%}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-3">
            <h3 class="card-title">Delete Station</h3>
            <form method="POST" class="card card-sm">
                {% csrf_token %}
                <div class="card-body row no-gutters align-items-center">
                    <p>Are you sure want to delete <b>{{station_detail.station_name}}</b> station?</p>
                    <div class="col-auto"><button type="submit" class="btn btn-danger">Delete</button></div>
                </div>
            </form>
        </div>
    </div>
</div>
   
{% endblock %}

RailwaySystem/train/templates/train/delete_train.html
{% include 'railway/base.html' %}
{% block body%}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-3">
            <h3 class="card-title">Delete Train</h3>
            <form method="POST" class="card card-sm">
                {% csrf_token %}
                <div class="card-body row no-gutters align-items-center">
                    <p>Are you sure want to delete <b>{{train_detail.train_name}}</b> train?</p>
                    <div class="col-auto"><button type="submit" class="btn btn-danger">Delete</button></div>
                </div>
            </form>
        </div>
    </div>
</div>
   
{% endblock %}

RailwaySystem/train/templates/train/get_route.html
{% include 'railway/base.html' %}
{% block body%}

<table id="train_table" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>Source Route</th>
            <th>Destination Route</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for route in routeData %}
        <tr>
            <td>{{ route.source_station }}</td>
            <td>{{ route.dest_station }}</td>
            <td>
                <a href="{% url 'train:updateRoute' route.id %}">
                    <i class="fa fa-pencil" aria-hidden="true"></i></a>
            </td>
            <td>    
                <a href="#" data-toggle="modal" data-target="#exampleModal">
                <i class="fa fa-trash-o" aria-hidden="true"></i></a>
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          <h5>Are you sure want to delete {{route.source_station}} -- {{route.dest_station}} route?</h5>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                          <a href="{% url 'train:deleteRoute' route.id %}" class="btn btn-primary">Delete</a>
                        </div>
                      </div>
                    </div>
                  </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}




<script type="text/javascript">
    $(document).ready(function() {
        $('#train_table').DataTable();
    } );
</script>

RailwaySystem/train/templates/train/get_routestation.html
{% include 'railway/base.html' %}
{% block body%}

<table id="train_table" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>Train Name</th>
            <th>Station Name</th>
            <th>Station Route</th>
            <th>Arrival Time</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for stationroute in routestations %}
        <tr>
            <td>{{ stationroute.train_number }}</td>
            <td>{{ stationroute.station_id }}</td>
            <td>{{ stationroute.route_id }}</td>
            <td>{{ stationroute.atime }}</td>
            <td>
                <a href="{% url 'train:updateRouteStation' stationroute.id %}">
                    <i class="fa fa-pencil" aria-hidden="true"></i></a>
            </td>
            <td>    
                <a href="{% url 'train:deleteRouteStatio' stationroute.id %}">
                <i class="fa fa-trash-o" aria-hidden="true"></i></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}


<script type="text/javascript">
    $(document).ready(function() {
        $('#train_table').DataTable();
    } );
</script>

RailwaySystem/train/templates/train/get_stations.html
{% include 'railway/base.html' %}
{% block body%}

<table id="train_table" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>Station ID</th>
            <th>Station Name</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {{stationData}}
        {% for station in stationData %}
        <tr>
            <td>{{ station.station_id }}</td>
            <td>{{ station.station_name }}</td>
            <td>
                <a href="{% url 'train:updateStation' station.station_id %}">
                <i class="fa fa-pencil" aria-hidden="true"></i>
                </a>
            </td>
            <td>    
                <a href="{% url 'train:deleteStation' station.station_id %}">
                <i class="fa fa-trash-o" aria-hidden="true"></i></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}


<script type="text/javascript">
    $(document).ready(function() {
        $('#train_table').DataTable();
    } );
</script>

RailwaySystem/train/templates/train/get_train.html
{% include 'railway/base.html' %}
{% block body%}

<table id="train_table" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>Train Number</th>
            <th>Train Name</th>
            <th>Source Station</th>
            <th>Destination Station</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for train in final_data %}
        <tr>
            <td>{{ train.train_number }}</td>
            <td>{{ train.train_name }}</td>
            <td>{{ train.source_station }}</td>
            <td>{{ train.dest_station }}</td>
            <td>
                <a href="{% url 'train:updateTrain' train.train_number %}">
                <i class="fa fa-pencil" aria-hidden="true"></i></a>
            </td>
            <td>    
                <a href="{% url 'train:deleteTrain' train.train_number %}">
                <i class="fa fa-trash-o" aria-hidden="true"></i></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}


<script type="text/javascript">
    $(document).ready(function() {
        $('#train_table').DataTable();
    } );
</script>

<!-- <div class="card-body row no-gutters align-items-center">
    <div class="row mb-3">
        <label for="TrainNumber" class="form-label">Train Number</label>
        <div class="col-sm-12">
            <input type="text" name="train_number">
        </div>
    </div>
    <div class="row mb-3">
        <label for="TrainName" class="form-label">Train Name</label>
        <div class="col-sm-12">
            <input type="text" name="train_name">
        </div>
    </div>
    <div class="row mb-3">
        <label for="selectroute" class="form-label">Select Route</label>
        <div class="col-sm-12">
            <select name="route" class="form-select">
            {% for i in routeData %}
                <option value="{{ i.id }}">{{i.source_station}}--{{i.dest_station}} </option>
            {% endfor %}
            </select>
        </div>
    </div>
    
    <div class="col-auto">
        <button type="submit" class="btn btn-success">Save</button>
    </div>
</div> -->